### ISSUE TITLE
continue slider and don’t jump back at the end

### ISSUE THREAD

**Issue by webzunft** [webgilde/advanced-ads-slider#15]
not sure if this is possible with some hacking, but right now it scrolls back through the whole slides when at the end.

**Comment by Zodiac1978** [comment]
This is possible with the infinite parameter:

```
$('.infinite-slider').unslider({
infinite: true
});
```

See the demo page: http://idiot.github.io/unslider/

**Comment by Zodiac1978** [comment]
Fixed with https://github.com/webgilde/advanced-ads-slider/commit/7cc5bd32e0d70148b18980b35b262d3e0eb57c02
