### ISSUE TITLE
fade does not work

### ISSUE THREAD

**Issue by webzunft** [webgilde/advanced-ads-slider#18]
when trying to use `fade` as the animation type, the slider breaks.
On the bottom of https://wpadvancedads.com/add-ons/slider/ is described how the animation type can be changed.

According to the unslider documentation this should work, but for some reason, it does only with the default option and `vertical`.

Further testing revealed that it doesn’t work outside of Advanced Ads in other default WordPress themes either, so there seems to be a general incompatibility.

Some resources:
- https://github.com/idiot/unslider/issues/283
- https://css-tricks.com/forums/topic/unslider-simple-jquery-slider-not-working/

I need a confirmation if there is a possible fix and how complicated it is. It should be something we can change in our code, but not something we need to put into the unslider library every time it is updated. Unless, the main developer adds it himself.

**Comment by Tymvie** [comment]
@webzunft please see https://github.com/webgilde/advanced-ads-slider/pull/25 and https://github.com/webgilde/advanced-ads-pro/pull/251. The first commit also fixes https://github.com/webgilde/advanced-ads-slider/issues/14

**Comment by webzunft** [comment]
works, thanks
