### ISSUE TITLE
Not working with error jQuery(...).unslider is not a function

### ISSUE THREAD

**Issue by PascalAnimateur** [webgilde/advanced-ads-slider#19]
On a freshly installed wordpress site, the plugin doesn't work with the following error in the console:

> jQuery(...).unslider is not a function

I tried using jQuery 2.1.4 and it still doesn't work.

Any ideas?!

**Comment by webzunft** [comment]
Thanks for reaching out.
Please make sure that jQuery and the unslider script are loaded before the slider is requested in the source code. They should not be moved to the footer or loaded deferred.

**Comment by PascalAnimateur** [comment]
It's an encoding issue with the unslider.min.js being served locally.. I 
tried deregistering the js file and re-enqueueing it from a CDN (raw 
github actually) and it worked in one of my tests.

I will report back with a solution sometime soon..

**Comment by webzunft** [comment]
Thanks. Looking forward to your feedback.

**Comment by webzunft** [comment]
Thank you for your code suggestion, which I am going to use in the next version.
