### ISSUE TITLE
not working with scripts in the footer

### ISSUE THREAD

**Issue by webzunft** [webgilde/advanced-ads-slider#23]
After implementing https://github.com/webgilde/advanced-ads-pro/pull/218 (scripts can be moved to the footer), the Slider does not work.

See http://ads.webgilde.com/test-slider-and-page-ads/

Please suggest a solution.

**Comment by Tymvie** [comment]
@webzunft in order to solve the problem, jQuery should be loaded in the header. If this is not desirable then we need to move this (and  similar) code to the footer https://github.com/webgilde/advanced-ads-slider/blob/master/public/public.php#L122

**Comment by webzunft** [comment]
@Tymvie but moving it only for non-js-loaded ads, right?

**Comment by Tymvie** [comment]
@webzunft, yes, if cache-busting is disabled

**Comment by webzunft** [comment]
@Tymvie is there something we can do to inforce this or just add a note for users to check that jQuery is loaded in the header?

**Comment by Tymvie** [comment]
@webzunft unfortunately I do not see a solution other than moving all js to the footer.

**Comment by webzunft** [comment]
ok, thanks.
