### ISSUE TITLE
add "fade" as an option.

### ISSUE THREAD

**Issue by webzunft** [webgilde/advanced-ads-slider#28]
Seems like many users are using this with the provided function, but it doesn’t work for everyone.

**Comment by Zodiac1978** [comment]
The feature itself doesn't work or it doesn't work with the provided function from the manual?

**Comment by webzunft** [comment]
@Zodiac1978 could you please set it up on one of our test sites? Last time I checked it worked.

**Comment by Zodiac1978** [comment]
@webzunft You have written "it doesn’t work for everyone" and I was just asking what exactly did not work in such a case. Are there any tickets/links you can provide? Maybe this is a theme/plugin conflict.

**Comment by webzunft** [comment]
ah, I see. I can’t remember, but that should not be a problem if that is just optional in the plugin.
