### ISSUE TITLE
make it harder for themes to override the slider

### ISSUE THREAD

**Issue by webzunft** [webgilde/advanced-ads-slider#29]
It is common for themes to override the slider CSS causing issues.

E.g.

```
.widget li {
    margin-left: 12px;
}
```

We need more rules to make sure that no padding or margin is added to slider elements.

**Comment by Zodiac1978** [comment]
The rules are there:
https://github.com/webgilde/advanced-ads-slider/blob/master/public/assets/css/slider.css#L1

This is a matter of the loading order. Plugin CSS could be loaded before Theme CSS and the specificity could be equal in which case the loading orders matters.

But we could add an "!important" to them to solve this.

```
.widget .unslider li, .unslider li {
margin: 0 !important;
padding: 0 !important;
border: 0 !important;
clear: none !important;
} 
```

To make sure we don't change other list-items as the ones we want to touch we could add more classes and a child combinator.

```
.unslider .unslider-wrap.unslider-carousel > li,
.widget .unslider .unslider-wrap.unslider-carousel > li {
margin: 0 !important;
padding: 0 !important;
border: 0 !important;
clear: none !important;
} 
```

What do you think about this?

**Comment by webzunft** [comment]
@Zodiac1978 I don’t think that `.unslider-wrap.unslider-carousel` would be needed, but please add the other rules
