### ISSUE TITLE
Filter is broken for arguments requiring single quotes

### ISSUE THREAD

**Issue by Zodiac1978** [webgilde/advanced-ads-slider#31]
We provide a way to change the arguments of the slider:
https://wpadvancedads.com/add-ons/slider/

```
function my_slider_adjustments( $settings ) {
$settings['speed'] = 100; // 100 milliseconds
$settings['animation'] = 'fade'; // change animation to fade
return $settings;
}
add_filter( 'advanced-ads-slider-settings', 'my_slider_adjustments' );
```

But I get this error message in the browser console if I add this:
ReferenceError: fade is not defined

The documentation (http://idiot.github.io/unslider/ - section Methods & Options especially) is reading like this:
```
$('.fading-slider').unslider({
animation: 'fade',
autoplay: true,
arrows: false
});
```

But the code on the website is like so:
```$localslider2021048454.unslider({ delay:2000, autoplay:true, nav:false, arrows:false, infinite:true, speed:100, animation:fade }```

I think the missing single quotes are the problem here and this would make sense, as the error message is "fade is not defined" (misinterpreting fade as a function).

Related HelpScout ticket: https://secure.helpscout.net/conversation/424544341/22262/?folderId=732992

**Comment by webzunft** [comment]
@Zodiac1978 In the previous example on the website we had `'\'fade'\'`, which worked. So maybe just change the manual.

**Comment by Zodiac1978** [comment]
This does not work, but it leads to a idea/solution for me:

I changed:
`$settings['animation'] = 'fade';`
to
`$settings['animation'] = "'fade'";`

And this works for me.

**Comment by webzunft** [comment]
@Zodiac1978 could you please adjust the manual like that?

**Comment by Zodiac1978** [comment]
@webzunft I can't, because this is not editable for me (It is on the addon page which is part of EDD and I have no permissions there).

And furthermore the client is still having issues I am investigating ...

**Comment by Zodiac1978** [comment]
I think the problem from the client is theme specific. Confirmed fix, even for multiple slider.

**Comment by webzunft** [comment]
I fixed the manual. @Zodiac1978 so we can close this?

**Comment by Zodiac1978** [comment]
Yes. :)
