### ISSUE TITLE
Broken fade option

### ISSUE THREAD

**Issue by Zodiac1978** [webgilde/advanced-ads-slider#32]
After https://github.com/webgilde/advanced-ads-slider/commit/1968746b77880a5ba6af421aa9ce98558fa2505d the fade option is broken, because we overwrite the negative margin from here: 
https://github.com/webgilde/advanced-ads-slider/blob/1968746b77880a5ba6af421aa9ce98558fa2505d/public/assets/css/slider.css#L21

Possible solution: Add `!important` to this line too.

**Comment by webzunft** [comment]
@Zodiac1978 could you please do that?
