### ISSUE TITLE
jQuery missing

### ISSUE THREAD

**Issue by webzunft** [webgilde/advanced-ads-slider#33]
I enabled WP Rocket without safe mode and all recent updates to make it compatible on http://ads.webgilde.com/test-slider-and-page-ads/ and it broke the first slider. Is that fixable?

**Comment by Tymvie** [comment]
@webzunft please see https://github.com/webgilde/advanced-ads-slider/pull/34
A have uploaded this branch to http://ads.webgilde.com

**Comment by webzunft** [comment]
thanks
