### ISSUE TITLE
unslider is not a function

### ISSUE THREAD

**Issue by webzunft** [webgilde/advanced-ads-slider#46]
We see this issue from time to time without always having the explanation.

Example from http://staging.webworksolution.ca/libas/

`$stagislider1066676347.unslider is not a function.`

jQuery is registered. What else could cause this? Could we not use `$` in front of variables?

**Comment by Tymvie** [comment]
@webzunft this script in the footer causes the issue: 
`<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" defer></script>`.
 It removes the Unslider script added in the header below the correct jQuery script that comes with WordPress. The site author needs to remove it. 

And this script:     

```JavaScript
$(document).ready(function () {
if(document.cookie.indexOf("ModelShow=true")<0) {
$('.newsletter_popup').modal('show');
}
})
```

should be replaced with:

```JavaScript
jQuery(document).ready(function () {
if(document.cookie.indexOf("ModelShow=true")<0) {
jQuery('.newsletter_popup').modal('show');
}
})
```

> Could we not use $ in front of variables?

we are allowed to use $

**Comment by webzunft** [comment]
Thanks. I also added this to our manual now.
