### ISSUE TITLE
Broken text floating with groups and slider

### ISSUE THREAD

**Issue by aahenning** [webgilde/advanced-ads-slider#47]
if there is a group in the slider the text is not floating around the ad. whether there is cache-busting enabled or not.

- slider without [cache-busting](http://test-setup.com/test-p98hwe/2019/10/17/slider-test/http://test-setup.com/test-p98hwe/2019/10/17/slider-test/)
- slider with [cache-busting](http://test-setup.com/test-p98hwe/2019/10/17/slider-cache-busting-test/)

[original site](https://www.bons-plans-malins.com/1-pizza-pizza-pai-gratuite-pour-1-achetee-pizza-emporter/)

**Comment by webzunft** [comment]
Updated documentation with a solution: https://wpadvancedads.com/manual/slider-issues/
